version: '3.1'

services:
  wordpressFpm:
    container_name: web1Fpm
    image: wordpress:5-fpm-alpine
    expose:
        - "9000"
    restart: unless-stopped
    environment:
      # same as db container_name
      WORDPRESS_DB_HOST: mariadb-web1
      WORDPRESS_DB_NAME: YOUR_DB_NAME
      WORDPRESS_DB_USER: YOUR_DB_USER
      WORDPRESS_DB_PASSWORD: YOUR_DB_PASSWORD
      WORDPRESS_WP_HOME: 'https://web1.YOURDOMAIN.XYZ'
      WORDPRESS_WP_SITEURL: 'https://web1.YOURDOMAIN.XYZ'
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - web1_network
  db:
    container_name: mariadb-web1
    image: mariadb:focal
    restart: unless-stopped
    volumes:
      - ./mariadb/data/:/var/lib/mysql/
      - ./log/mysql:/var/log/mysql
    networks:
      - web1_network
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_DB_ROOT_PASSWORD
      MYSQL_DATABASE: YOUR_DB_NAME
      MYSQL_USER: YOUR_DB_USER
      MYSQL_PASSWORD: YOUR_DB_PASSWORD
    restart: unless-stopped
  nginx:
    container_name: 'nginx-web1'
    image: nginx:alpine
    expose:
     - 80
    environment:
      HTTP_PORT: 80
      VIRTUAL_HOST: web1.YOURDOMAIN.XYZ
      LETSENCRYPT_HOST: web1.YOURDOMAIN.XYZ
      LETSENCRYPT_EMAIL: "YOUR_EMAIL@ABCMAIL.COM"
    volumes:
      - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - ./cache/nginx:/var/cache/nginx
      - ./wordpress:/var/www/html
    networks:
      - web1_network
      - webproxy_network
    restart: unless-stopped
volumes:
    wordpress:
    db:
networks:
    web1_network:
        driver: bridge
    webproxy_network:
        external: true
