version: "3.1"

services:
  db:
    container_name: "db-webapp1"
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: DB_NAME
      POSTGRES_USER: DB_USERNAME
      POSTGRES_PASSWORD: DB_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - dogtrack_network
  #service name here must be the same as in /reverseproxy/nginx.conf
  nextjs:
    container_name: 'nextjs-webapp1'
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Bangkok
    networks:
      - webapp1_network
    depends_on:
      - db
    restart: unless-stopped
  reverseproxy:
    container_name: 'revproxy-webapp1'
    build: ./reverseproxy
    expose:
     - 80
    environment:
      HTTP_PORT: 80
      VIRTUAL_HOST: webapp1.YOURDOMAIN.XYZ
      LETSENCRYPT_HOST: webapp1.YOURDOMAIN.XYZ
      LETSENCRYPT_EMAIL: "YOUR_EMAIL@ABCMAIL.COM"
    networks:
      - webapp1_network
      - webproxy_network
    restart: unless-stopped
networks:
  webapp1_network:
    driver: bridge
  webproxy_network:
    external: true
